### ISSUE TITLE
Points ordering - Automatic and Manual

### ISSUE THREAD

**Issue by caoyuan96421** [zvant/FourierTransformFit#12]
Please leave related comments in this issue.

**Comment by caoyuan96421** [comment]
Implementation of automatic ordering only for convex polygon case - zvant

**Comment by zvant** [comment]
I think actually we do not need to implement the convex hull algorithm. It could be down using the following simple algorithm (will only work for points that form a convex polygon):
1. find the "center" C0 of the sample points. it is actually the first coefficient.
2. for every points [z_k] in sample, calculate the angle [theta_k] of z_k-C0
3. sort points according to [theta_k]

these steps could find our convex hull.

**Comment by zvant** [comment]
And if the points do not form a convex polygon, the algorithm above would not make things worse. Just not working well.

**Comment by zvant** [comment]
I add _reOrder()_ to _FourierTransform_. Now it is called by _transform()_. We should add a button to do this (maybe one more button to restore the original order).

**Comment by zvant** [comment]
![examples](https://t.williamgates.net/image-A611_554A1747.jpg)
This method works well for convex polygon case, not bad for star-like case.

**Comment by caoyuan96421** [comment]
Automatic ordering and manual ordering is functional now. Close #12.
