### ISSUE TITLE
Javadoc generated

### ISSUE THREAD

**Issue by zvant** [zvant/FourierTransformFit#13]
Now using in src/

javadoc -private -d ../doc/ -J-Duser.language=en_US -encoding UTF-8 -charset UTF-8 -docencoding UTF-8 -subpackages fourier

**Comment by caoyuan96421** [comment]
The whole project now seems to be running in Java 1.5 compatibility mode on my computers. I want to rebuild the whole project.

**Comment by zvant** [comment]
Do you mean you want to refactor the code? Rebuilding will not change anything.

**Comment by caoyuan96421** [comment]
I meant copying all sources to a complete new project.

**Comment by zvant** [comment]
I cant see how that could fix the compatibility problem...

**Comment by zvant** [comment]
Maybe some configuration files for the IDE should be modified.

**Comment by caoyuan96421** [comment]
I have recreated the project using Netbeans. Can you open it with eclipse now?

**Comment by zvant** [comment]
Cannot. trying to create a new project and copy code to it. then add the cfg files to current folder. see if that works.

**Comment by zvant** [comment]
it worked. pushed.
