### ISSUE TITLE
Coefficients updating

### ISSUE THREAD

**Issue by caoyuan96421** [zvant/FourierTransformFit#7]
To update the coefficients table that is bound with the array `coef[]`, add the following code snippet

``` Java
for (int i = 0; i < n; i++) {
  coefficients_table.setValueAt(coef[i].re(), i, 1);
  coefficients_table.setValueAt(coef[i].im(), i, 2);
  coefficients_table.setValueAt(coef[i], i, 3);
}
```

which is already there at 353L of `GraphicFitting.java`

**Comment by zvant** [comment]
How about the coordinate system? The sample points are stored in the ArrayList<Point2D> sample_points. How should it be converted to Complex Array so the curve could to be painted within the panel?
