### ISSUE TITLE
some possible methods to improve the algorithm - sorting points

### ISSUE THREAD

**Issue by zvant** [zvant/FourierTransformFit#9]
If we sort the sample points by their angles, thus form a clock-wised order, the absolute value of coefficients for high frequency items could be reduced.

**Comment by zvant** [comment]
Or we could divide sample points to several small groups and perform transformation to each group. Just like piecewise polynomials we used to avoid [Runge's phenomenon](http://en.wikipedia.org/wiki/Runge%27s_phenomenon) in Lagrange polynomial interpolation. Maybe something like spline interpolation.

**Comment by zvant** [comment]
We need someone who knows how to handle signals.

**Comment by caoyuan96421** [comment]
Using piece wise function will void our purpose of using circles to approximate paths
